
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nest_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://nest:nest@postgres:5432/nest_db?schema=public
      NODE_ENV: production
      PORT: 4000
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN:-}
      FROM_EMAIL: ${FROM_EMAIL:-}
      FROM_NAME: ${FROM_NAME:-Defekt Report}
      OWNER_EMAIL: ${OWNER_EMAIL:-}
      DRIVE_PARENT_FOLDER_ID: ${DRIVE_PARENT_FOLDER_ID:-}
    ports:
      - '4000:4000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - '8080:80'

volumes:
  db_data:
